[package]
name = "slack"
version = "0.13.0"
authors = ["Benjamin Elder <bentheelder@gmail.com>", "Matt Jones <mthjones@gmail.com>"]
repository = "https://github.com/slack-rs/slack-rs.git"
documentation = "http://slack-rs.github.io/slack-rs/slack/index.html"
description = "slack realtime messaging client: https://api.slack.com/bot-users"
license = "Apache-2.0"

[dependencies]
websocket = "0.15.2"
hyper = "0.8.0"
rustc-serialize = "0.3.18"
slack_api = { git = "https://github.com/strain-113/slack-rs-api", branch = "optional-text-attachment" }

